apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-server
  labels:
    app: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webpage
          image: shajalahamedcse/webpage
          ports:
            - containerPort: 80
